/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Poke_University;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Window window = new Window(1000,1000);
        Panel pan = new Panel();

    }
}
